/// Renders a [HealthReport] to a PDF document. This is the only place the
/// Flutter `pdf` package is used; the report content model lives in the engine.
library;

import 'dart:typed_data';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../engine/battery_health.dart';

PdfColor _severityColor(Severity s) {
  switch (s) {
    case Severity.ok:
      return PdfColors.green700;
    case Severity.info:
      return PdfColors.blue700;
    case Severity.warning:
      return PdfColors.orange800;
    case Severity.critical:
      return PdfColors.red800;
  }
}

Future<Uint8List> buildReportPdf(HealthReport report) async {
  final doc = pw.Document();
  final readings = report.readings.values.toList()
    ..sort((a, b) => (a.signal.group ?? '').compareTo(b.signal.group ?? ''));

  doc.addPage(
    pw.MultiPage(
      pageFormat: PdfPageFormat.a4,
      build: (context) => [
        pw.Header(
          level: 0,
          child: pw.Text('Battery Health Report',
              style: const pw.TextStyle(fontSize: 22, fontWeight: pw.FontWeight.bold)),
        ),
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
              pw.Text('Vehicle: ${report.vehicle}'),
              if (report.vin != null) pw.Text('VIN: ${report.vin}'),
              pw.Text('Generated: ${report.generatedAt.toUtc().toIso8601String()}'),
            ]),
            pw.Container(
              padding: const pw.EdgeInsets.symmetric(horizontal: 12, vertical: 6),
              decoration: pw.BoxDecoration(
                color: _severityColor(report.overallSeverity),
                borderRadius: pw.BorderRadius.circular(6),
              ),
              child: pw.Text(report.overallSeverity.name.toUpperCase(),
                  style: const pw.TextStyle(color: PdfColors.white)),
            ),
          ],
        ),
        pw.SizedBox(height: 16),
        pw.Text('Key metrics',
            style: const pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
        pw.SizedBox(height: 6),
        pw.TableHelper.fromTextArray(
          headers: const ['Metric', 'Value'],
          data: report.metrics.entries
              .map((e) => [e.key, e.value?.toStringAsFixed(3) ?? '—'])
              .toList(),
        ),
        pw.SizedBox(height: 16),
        pw.Text('Warnings',
            style: const pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
        pw.SizedBox(height: 6),
        ...report.warnings.map((w) => pw.Bullet(
              text: '[${w.severity.name.toUpperCase()}] ${w.message}',
            )),
        pw.SizedBox(height: 16),
        pw.Text('All readings',
            style: const pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
        pw.SizedBox(height: 6),
        pw.TableHelper.fromTextArray(
          headers: const ['Group', 'Signal', 'Value', 'Unit'],
          data: readings
              .map((r) => [
                    r.signal.group ?? '',
                    r.signal.name,
                    r.value.toStringAsFixed(3),
                    r.unit,
                  ])
              .toList(),
        ),
        pw.SizedBox(height: 24),
        pw.Text(
          'Generated by OBD Battery Diagnostics. Values are read-only OBD '
          'diagnostics; heuristic thresholds are for guidance, not a '
          'manufacturer certification.',
          style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
        ),
      ],
    ),
  );

  return doc.save();
}
